#!/bin/sh
# install libpcap-dev if you have that error :
# pcapdumper.cc:12:18: fatal error: pcap.h: No such file or directory
if [ $(whoami) != "root" ]; then echo "only root can do that"; exit 1; fi
DEBIAN_FRONTEND=noninteractive apt-get install --no-upgrade -qq python-pcapy g++ python-dev libpcap-dev
cd ../packages/python/pcapy
python setup.py build
python setup.py install
cd -
